# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Edify
email: kristen@edifyedu.com
description: 'Edify is a learning & development consultancy that removes the pain of people operations with stellar onboarding, manager development, and knowledge management.'
# baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://edifyedu.com/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: edifyedu
github_username:  edifyedu
timezone: America/Los_Angeles

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - config.ru
  - Procfile
  - READMD.md
  - vendor

collections:
  pages:
    output: true
    permalink: /:name

  posts:
    output: true
    permalink: /blogs/:title


#Prose.io config details
prose:
  rooturl: ''
  siteurl: ''
  media: 'img/blog'
  ignore:
    - index.md
    - _config.yml
    - /_layouts
    - /_includes
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "single-post-layout"
      - name: "title"
        field:
          element: "text"
          label: "title"
      - name: "category"
        field:
          element: "select"
          label: "Add Category"
          placeholder: "Choose Category"
          options:
            - name: "Alternative Learning"
              value: "alternative_learning"
            - name: "Onboarding"
              value: "onboarding"
            - name: "Learning Management"
              value: "learning_management"
            - name: "Managers"
              value: "managers"
            - name: "Instructional Design"
              value: "instructional_design"
            - name: "Human Centered Design"
              value: "human_centered_design"
      - name: "feature_post"
        field:
          element: "checkbox"
          label: "Feature Post"
          help: "Feature posts are displayed on the home page. Check the box if this post is a feature post."
          value: "true"
      - name: "width"
        field:
          element: "select"
          label: "Post Type"
          placeholder: "select one"
          options:
            - name: "Half"
              value: "half"
            - name: "Full"
              value: "full"
      - name: "image_thumb"
        field:
          element: text
          label: "Image Thumb File Name"
          help: "Enter the name of the image file with the extension, ie: featuredpost2-thumb.png"
          value: ""
          placeholder: ""
      - name: "image"
        field:
          element: text
          label: "Image File Name"
          help: "Enter the name of the image file with the extension, ie: featuredpost2.png"
          value: ""
          placeholder: ""
      - name: "image_alt"
        field:
          element: text
          label: "Image Alt Text"
          help: "Descriptive text for each image - important for universal design"
          value: ""
          placeholder: "Edify Blog Post Image"
      - name: "short_description"
        field:
          element: textarea
          label: "Short Description"
          help: "This text will be displayed on the blog listing page"
          value: ""
          placeholder: ""
