services_title: "What can Edify do for you?"
services_subtitle: "Edify is a learning strategy firm that removes the employee development challenges from scaling your startup."

service_one: "Onboarding"
service_one_text: "Onboarding that scales with you and cuts time to productivity in half."

service_two: "Managers"
service_two_text: "Technical managers who aren’t just technical: Invest in helping managers be better people leaders."

service_three: "Knowledge"
service_three_text: "Remove barriers to getting ramped up by untangling your knowledge management ecosystem."