service_one: "Onboarding"
service_one_text: "Onboarding that scales with you and cuts time to productivity in half - for every level of your business."

service_two: "Managers"
service_two_text: "Invest in helping managers be better people leaders through targeted development."

service_three: "L&D Strategy"
service_three_text: "Deliver the learning programs your team needs, in the right timeframe and budget."
